# Generated by Django 3.1.6 on 2021-05-22 23:23

import dashboard.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('organization_description', models.CharField(blank=True, max_length=1024)),
                ('organization_logo', models.FileField(default='default-logo.png', upload_to=dashboard.models.get_upload_logo_path)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('cause', models.CharField(blank=True, max_length=500)),
                ('large_media', models.FileField(blank=True, upload_to=dashboard.models.get_upload_large_media_path)),
                ('large_image', models.CharField(blank=True, max_length=1000)),
                ('large_media_url', models.CharField(blank=True, max_length=1000)),
                ('large_media_thumbnail', models.CharField(blank=True, max_length=300)),
                ('large_media_cover', models.CharField(blank=True, max_length=300)),
                ('large_media_cover_small', models.CharField(blank=True, max_length=300)),
                ('large_is_video', models.BooleanField(blank=True, default=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('has_end_date', models.BooleanField(default=True)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('has_goal_amount', models.BooleanField(default=True)),
                ('goal_amount', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('second_email', models.EmailField(blank=True, max_length=254)),
                ('is_email_private', models.BooleanField(default=True)),
                ('mobile', models.CharField(blank=True, max_length=12)),
                ('is_mobile_private', models.BooleanField(default=True)),
                ('your_title', models.CharField(blank=True, max_length=100)),
                ('is_your_title_private', models.BooleanField(default=True)),
                ('is_campaign_searchable', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, max_length=1000)),
                ('is_campaign_private', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('raised_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('raised_percentage', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to=dashboard.models.get_upload_media_path)),
                ('image', models.CharField(blank=True, max_length=1000)),
                ('media_url', models.CharField(blank=True, max_length=1000)),
                ('thumbnail', models.CharField(blank=True, max_length=300)),
                ('is_video', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dashboard.campaign')),
            ],
            options={
                'db_table': 'medias',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='dashboard.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'managers',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to=settings.AUTH_USER_MODEL),
        ),
    ]
